name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release --no-restore
    - name: Build (Unity)
      run: dotnet build --no-restore --configuration Release-Unity --no-restore
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Nightscout.Net
        path: |
          Nightscout.Net/bin/Release/netstandard2.0/Nightscout.Net.dll
          Nightscout.Net/bin/Release/netstandard2.0/Nightscout.Net.pdb
    - name: Upload (Unity)
      uses: actions/upload-artifact@v2
      with:
        name: Nightscout.Net (Unity)
        path: |
          Nightscout.Net/bin/Release-Unity/netstandard2.0/Nightscout.Net.dll
          Nightscout.Net/bin/Release-Unity/netstandard2.0/Nightscout.Net.pdb